### ISSUE TITLE
Support cache with time to live for entries

### ISSUE THREAD

**Issue by JoshMcguigan** [tylerreisinger/cache-macro#6]
A common use case for cacheing would be when making network calls to external services. In this case, a user might want to use a backing cache which supports a time to live for entries to ensure the data doesn't get stale. 

I've created an [expiring_map](https://github.com/JoshMcguigan/expiring_map) crate which could provide the backing data storage for this, but supporting the `expiring_map` cache within the `lru-cache-macro` would require some modifications to this crate. 

I'd be wiling to attempt making a PR to add the necessary changes, if this is something you are interested in. One larger issue, however, is that it may make sense to rename this repo/crate to something more general (perhaps simply `cache-macro`?). Let me know what you think.

**Comment by tylerreisinger** [comment]
I think that's a good idea. It may be smart to add a trait that the lru_cache macro calls through in order to support a more structured interface for other cache types to implement, although I think this would require an auxiliary crate as a proc-macro crate cannot expose anything else. 

The current name is a bit unfortunate, as it started as a toy to learn proc macros and grew in scope over time. Once support for your cache goes in, we can soft deprecate the old crate and push a new one with a better name, as well as rename the repo.

**Comment by tylerreisinger** [comment]
I'm wondering if it makes sense to leave the `#[lru_cache(...)]` macro availabe as shorthand for `#[cache(LruCache : LruCache::new(...)]` to ease migration and decrease typing for that case.
